### ISSUE TITLE
play musics are too slow now

### ISSUE THREAD

**Issue by apierre55000** [jellyfin/jellyfin-desktop#196]
hello all,

when i click on song to play it, it takes +-5 seconds to open and play it.
but videos launch directly why there are so differences ?

the audio format is in flac and mp3

i remember that the songs launched instantly before the last update (1.10)

could you make anything to resolve this issue ?

thank you all :)

**Comment by iwalton3** [comment]
I'm not sure. Can you post the logs? https://github.com/jellyfin/jellyfin-desktop/wiki/Sending-Logs

Disclaimer that this client really doesn't make much of an effort to support music right now. It hasn't been too big of a priority yet because there are other options, but of course contributions will be accepted.

**Comment by iwalton3** [comment]
I did a quick test and music plays instantly for me on this client. I really do need logs to know what is happening.

**Comment by apierre55000** [comment]
hello, the problem is about my ethernet card configuration, it's ok now, sorry for my report... have a nice day !
